### ISSUE TITLE
가독성 챙기기

### ISSUE THREAD

**Issue by aisolab** [aisolab/html-css101#4]
같은 HTML tag를 서로 다른 CSS로 꾸미려면, 개별 HTML tag에 class를 적용하고,  `*.css` 파일 내에서 HTML tag와 `class`에 따라 CSS를 작성한다. 아래의 CSS는 `big-font`, `small-font` class에 해당하는 HTML tag를 서로 다른 `font-size`를 가지도록 하는 예이다.

```css
.big-font {
    font-size: 40px;
}

.small-font {
    font-size: 15px;
}
```
