### ISSUE TITLE
중앙에 배치하기

### ISSUE THREAD

**Issue by aisolab** [aisolab/html-css101#5]
여러 HTML tag를 하나로 묶으려면 `<div>` tag를 활용한다. `<div>` tag로 묶인 HTML tag들을 CSS로 일괄적으로 꾸밀 수 있다.  아래는 예시이다.

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>김보섭의 이력서</title>
        <link rel="stylesheet" href="codelion.css">
    </head>
    <body>
        <div class="mainbox">
            <h1>김보섭</h1>
            <p>HTML/CSS</p>
        </div>
        <footer>copyright CODE LION. All rights reserved.</footer>
    </body>
</html>
```
```css
footer {
    text-align: center;
    background-color: #121212;
    color: #919191;
    font-size: 12px;
}

.mainbox {
    border: 1px solid #ebebeb; /*두께 방식 색깔*/
    width: 610px;
    text-align: center;
    margin-left: auto;
    margin-right: auto;
}
```
