### ISSUE TITLE
구글 웹 폰트 사용하기

### ISSUE THREAD

**Issue by aisolab** [aisolab/html-css101#8]
구글 웹 폰트를 사용하는 경우 CSS 파일에 `@import`를 하면된다. 아래는 그 예시이다. 또한 이 폰트를 모든 HTML tag에 사용하기위해서는 CSS 파일에 아래와 같이 작성한다.

```css
@import url('https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,800&display=swap');

/*
    * 자리에는 tag가 들어가거니, class 이름이 들어가지면 *을 그대로 냅두면, HTML 모든 tag에 
    {}안에 기입하는 내용을 적용하게된다.
*/
* {
    font-family: 'Montserrat'
}
...
```
